spring:
  application:
    name: time-log

  datasource:
    url: jdbc:postgresql://localhost:5432/time-log
    username: postgres
    password: postgres
    hikari:
      connection-timeout: 1200
      validation-timeout: 600
      max-lifetime: 12000
      idle-timeout: 6000
      connection-init-sql: "SELECT 1"

schedule:
  db:
    record:
      cron: 0/1 * * * * ?
    check:
      cron: 0/5 * * * * ?